### ISSUE TITLE
Missing declare of MODULE_LICENSE in imq.ko

### ISSUE THREAD

**Issue by gnif** [imq/linuximq#10]
imq.ko is mising the declare `MODULE_LICENSE("GPL")` which prevents it from accessing the exported methods in `xt_IMQ`.

**Comment by imq** [comment]
which patch you use?

**Comment by gnif** [comment]
Sorry, it was 3.18 with imq configured as a module.

**Comment by gnif** [comment]
For reference, fixed in 0312a53a71fba094bbdf71721aa86f2ccf6908d6
