### ISSUE TITLE
missing MODULE_LICENSE

### ISSUE THREAD

**Issue by wongsyrone** [imq/linuximq#18]
WARNING: modpost: missing MODULE_LICENSE() in drivers/net/imq.o

**Comment by gfreewind** [comment]
Which file or patch?

**Comment by wongsyrone** [comment]
I think it should be drivers/net/imq.c in https://github.com/imq/linuximq/blob/master/latest/linux-3.18-imq.diff. can you check all patches related to drivers/net/imq.c?

**Comment by gfreewind** [comment]
There is one line "MODULE_LICENSE("GPL");" in linux-3.18-imq.diff.

**Comment by wongsyrone** [comment]
but it is in file `net/netfilter/xt_IMQ.c`

**Comment by gfreewind** [comment]
Ok. I get it. Thanks

**Comment by wongsyrone** [comment]
@gfreewind  sorry to bother you, but I want to ask why there's no `MODULE_ALIAS_RTNL_LINK("imq")` in linux-3.18-imq.diff.

**Comment by gfreewind** [comment]
Thanks your finding.
I think it is lost by chance. I have fixed it now.

**Comment by wongsyrone** [comment]
@gfreewind  the line you added has two plus sign(++) at the front of line.

**Comment by gfreewind** [comment]
thanks again :(
It is the my fault. I am busy today, so that I have not tested it.
