### ISSUE TITLE
IMQ crashing and rebooting router

### ISSUE THREAD

**Issue by jsalatiel** [imq/linuximq#30]
I have installed IMQ on my router and set up a few rules, but the moment the imq0 interface goes up the router reboots . The only info i can see in the netconsole and syslog is : 
Oct 17 21:55:29 meumodem.lan MeuNovoModem: kernel: [  165.870000] skbuff: IMQ: kfree_skb: skb->cb_next: 862cad80
Oct 17 21:55:29 meumodem.lan MeuNovoModem: kernel: [  165.880000] skbuff: IMQ: kfree_skb: skb->nf_queue_entry != NULL
Oct 17 21:55:30 meumodem.lan MeuNovoModem: kernel: [  166.120000] skbuff: IMQ: kfree_skb: skb->cb_next: 85aee340
Oct 17 21:55:30 meumodem.lan MeuNovoModem: kernel: [  166.130000] skbuff: IMQ: kfree_skb: skb->nf_queue_entry != NULL
Oct 17 21:55:30 meumodem.lan MeuNovoModem: kernel: [  166.170000] skbuff: IMQ: kfree_skb: skb->cb_next: 85aee440
Oct 17 21:55:30 meumodem.lan MeuNovoModem: kernel: [  166.180000] skbuff: IMQ: kfree_skb: skb->nf_queue_entry != NULL
Oct 17 21:55:30 meumodem.lan MeuNovoModem: kernel: [  166.420000] skbuff: IMQ: kfree_skb: skb->cb_next: 85aeeb00
Oct 17 21:55:30 meumodem.lan MeuNovoModem: kernel: [  166.430000] skbuff: IMQ: kfree_skb: skb->nf_queue_entry != NULL
Oct 17 21:55:30 meumodem.lan MeuNovoModem: kernel: [  166.880000] skbuff: IMQ: kfree_skb: skb->cb_next: 83014580
Oct 17 21:55:30 meumodem.lan MeuNovoModem: kernel: [  166.880000] skbuff: IMQ: kfree_skb: skb->nf_queue_entry != NULL

# uname -a
Linux MeuNovoModem 3.18.21 #7 Fri Oct 02 11:04:58 GMT 2015 mips GNU/Linux

The router has 128Mb RAM, and just one user and it reboots almost idle.

**Comment by gfreewind** [comment]
Which version are you using?

**Comment by gfreewind** [comment]
Hi
It should be fixed by me with 4.x kernel patch.

Now I merge the fix to 3.18 patch. 
Could you try the latest 3.18 patch now?

**Comment by jsalatiel** [comment]
I will do it next monday. Thanks !

**Comment by jsalatiel** [comment]
Where can  i  downloaded ? The last change on master appears to be a few months ago.

**Comment by gfreewind** [comment]
Sorry, I forget merge the pull request to linuximq from my branch.
Now you could try it. 
The link is https://github.com/imq/linuximq/commit/ce7662597b926983da4626c04917c3d24eb32802

**Comment by tianxiangwei** [comment]
I have a crash when running IMQ on kernel 3.10.49 via the patch https://github.com/imq/linuximq/blob/master/kernel/v3.x/linux-3.10.27-imq.diff
log belowed:
  988.050000] skbuff: IMQ: kfree_skb: skb->cb_next: 9af92440
[  988.060000] skbuff: IMQ: kfree_skb: skb->nf_queue_entry != NULL
[  988.550000] CPU 1 Unable to handle kernel paging request at virtual address 00000009, epc == 80152fb4, ra == 801bb268
[  988.560000] Oops[#1]:
[  988.560000] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 3.10.49 #1
[  988.560000] task: 9bc528c8 ti: 9bc70000 task.ti: 9bc70000
[  988.570000] $ 0   : 00000000 00000001 80390000 fffffffe
[  988.580000] $ 4   : 9b110500 9b110500 00000000 9ac35000
[  988.580000] $ 8   : 00000300 00000000 00000000 00000000
[  988.590000] $12   : 8038e0c0 00000600 00000001 00000001
[  988.590000] $16   : 9b110500 00000000 9b110500 00000000
[  988.600000] $20   : 9abbe500 c220a0d8 00000000 00000000
[  988.600000] $24   : 8036666c 80207788                  
[  988.610000] $28   : 9bc70000 9bc71c60 00000008 801bb268
[  988.610000] Hi    : 00000005
[  988.610000] Lo    : 3a8aaa55
[  988.620000] epc   : 80152fb4 ip_rcv_finish+0x50/0x4b0
[  988.620000]     Not tainted
[  988.630000] ra    : 801bb268 nf_reinject+0x120/0x1b0
[  988.630000] Status: 1100fc03 KERNEL EXL IE 
[  988.630000] Cause : 00800008
[  988.640000] BadVA : 00000009
[  988.640000] PrId  : 0001992f (MIPS 1004Kc)

Is that the same issue?How to fix it? try the patch 3.18 to kernel 3.10.49? thanks!
