### ISSUE TITLE
Patch won`t apply on stable 4.1.12

### ISSUE THREAD

**Issue by paszczus** [imq/linuximq#31]
latest linux-4.1-imq.patch fails:

oot@rwl0:/home/kernel/linux-4.1.12# patch -p1 < ../linux-4.1-imq.diff
patching file drivers/net/Kconfig
patching file drivers/net/Makefile
patching file drivers/net/imq.c
patching file include/linux/imq.h
patching file include/linux/netdevice.h
patching file include/linux/netfilter/xt_IMQ.h
patching file include/linux/netfilter_ipv4/ipt_IMQ.h
patching file include/linux/netfilter_ipv6/ip6t_IMQ.h
patching file include/linux/skbuff.h
Hunk #6 succeeded at 3233 (offset -1 lines).
patching file include/net/netfilter/nf_queue.h
Hunk #1 succeeded at 31 (offset 2 lines).
patching file include/net/pkt_sched.h
patching file include/uapi/linux/netfilter.h
patching file net/core/dev.c
Hunk #2 succeeded at 2645 (offset -4 lines).
Hunk #3 succeeded at 2688 (offset -4 lines).
Hunk #4 succeeded at 2777 (offset -4 lines).
patching file net/core/skbuff.c
Hunk #4 succeeded at 3450 (offset 1 line).
patching file net/ipv6/ip6_output.c
patching file net/netfilter/Kconfig
patching file net/netfilter/Makefile
patching file net/netfilter/core.c
Hunk #1 succeeded at 179 (offset 1 line).
patching file net/netfilter/nf_internals.h
Hunk #1 FAILED at 18.
1 out of 1 hunk FAILED -- saving rejects to file net/netfilter/nf_internals.h.rej
patching file net/netfilter/nf_queue.c
Hunk #2 succeeded at 146 (offset 17 lines).
Hunk #3 succeeded at 157 (offset 17 lines).
Hunk #4 succeeded at 253 (offset 17 lines).
patching file net/netfilter/xt_IMQ.c
patching file net/sched/sch_generic.c

**Comment by gfreewind** [comment]
Thanks your response. It is fixed now.

**Comment by paszczus** [comment]
@gfreewind  where? Cause i don`t see newer version of linux-4.1-imq.diff at github?

**Comment by paszczus** [comment]
ok nevermind, i see pull request ;) thanks!
