### ISSUE TITLE
IMQ on kernel 3.10.98

### ISSUE THREAD

**Issue by erik4nd3** [imq/linuximq#36]
Hi,

I'm running IMQ on kernel 3.10.98 via the patch http://linuximq.mantech.ro/patches/patch-imqmq-3.10.27.diff.xz. Everything seem to work fine. However, when loading traffic to the machine and running tcpdump on the 'any' interface (linux cooked mode) I get a lot of these messages in the kernel log:

[611512.049026] skbuff: IMQ: kfree_skb: skb->nf_queue_entry != NULL

I've reproduced the issue on different 3.10.x versions and on the 3.2.x kernel versions. Running tcpdump on a specific (imq enabled) interface doesn't introduce the error message. E.g. tcpdump -ni eth0.

The machine has been under heavy load with a running tcpdump on the 'any' interface for a week and the kernel doesn't panic but has yielded a lot of the above error message. Can I neglect the error message?

Any ideas?

Thanks and regards,

Erik

**Comment by k0ste** [comment]
What you wanna see on -i imq? There is nothing in fact, it's empty.
You only can see interface speeds via bwm-ng or something looking to /proc/net/dev.
I never heard that can watch the traffic on imq interface.

Regards.

**Comment by erik4nd3** [comment]
Thanks for the reply. I don't want to see anything on the imq interfaces. However I want to be able to use the tcpdump option -i any to see traffic on e.g. eth0 and eth1 on the same time. Without getting these error in the kernel log.

Regards,

Erik

**Comment by k0ste** [comment]
@erik4nd3, now I understand. BTW, on Kernerl 4.4 this problem is absent.

**Comment by erik4nd3** [comment]
Good. Thank you for the information!

Regards,

Erik
