### ISSUE TITLE
IMQ for 4.5

### ISSUE THREAD

**Issue by PLumowina** [imq/linuximq#37]
is there a change to have working patch for new stable linux kernel ?

**Comment by k0ste** [comment]
Hi.
I test now (4 days okay) with 4.4.5 this patch https://github.com/k0ste/linuximq/blob/linux-4.4.5/kernel/v4.x/linux-4.4.5-imq.diff

Try apply to 4.5 and post result.

**Comment by PLumowina** [comment]
Its not working - there are some changes in skbuff.h :/
[imq-4.5_error.txt](https://github.com/imq/linuximq/files/197771/imq-4.5_error.txt)

**Comment by k0ste** [comment]
@PLumowina, try this https://github.com/k0ste/linuximq/blob/linux-4.5/kernel/v4.x/linux-4.5-imq.diff
Don't test it, just make kernel.

**Comment by k0ste** [comment]
@PLumowina, any results?
