### ISSUE TITLE
The maximum number of IMQ devices

### ISSUE THREAD

**Issue by li-ma** [imq/linuximq#4]
I'd like to create IMQ devices as much as possible by modifying the source code: IMQ_MAX_DEVS. I wonder how many devices I can create for a certain kernel, like 3.13.

**Comment by imq** [comment]
you could increase the default number and test it. I've never needed more than 4 imq interfaces

**Comment by li-ma** [comment]
OK. I changed my schema to just take advantage of 2 imq interfaces.
