### ISSUE TITLE
iptables-restore cannot work with imq

### ISSUE THREAD

**Issue by li-ma** [imq/linuximq#5]
Some rules just like:
-t mangle -A POSTROUTING -d 192.168.5.0/24 -j IMQ --todev 0

iptables-restore cannot work properly and throw the exception:

iptables-restore v1.4.7: unknown option `--todev'
Try `iptables-restore -h' or 'iptables-restore --help' for more information.

**Comment by li-ma** [comment]
Then I tried to use iptables to see what happened:

[root@vrouter ~]# sudo iptables -t mangle -A POSTROUTING -d 192.168.5.0/24 -j IMQ --todev 0
iptables v1.4.7: unknown option `--todev'
Try `iptables -h' or 'iptables --help' for more information.

But here, it is working.
[root@vrouter ~]# iptables -t mangle -A POSTROUTING -d 192.168.5.0/24 -j IMQ --todev 0

**Comment by pfactum** [comment]
You should have two different versions of iptables installed (distro and imq-aware) somewhere under /usr/bin and /usr/local/bin.

**Comment by li-ma** [comment]
Yes, you are totally right. I should remove distro package in advance. Thanks a lot.
