### ISSUE TITLE
The patch for kernel 4.9 is incomplete

### ISSUE THREAD

**Issue by vel21ripn** [imq/linuximq#58]
Fix is available in the pull-request #57

**Comment by micron10** [comment]
Hi
Yes first is fix problem
But next problem is : after machine boot with iptables rulls have access and work.
next problem if have iptables rulls and imq is up machine work and not have problem.
but after down imq0 machine stop access .
i go to keyboard and up imq direct from console and machine start access.

**Comment by vel21ripn** [comment]
Fixed in commit af2771e
