### ISSUE TITLE
Do you have any plan to improve the performance of IMQ?

### ISSUE THREAD

**Issue by gfreewind** [imq/linuximq#6]
Hi ,

Firstly, thanks you for sharing the IMQ.
I did performance tests recently. 
The HTTP RPS could reach 14 k/s without IMQ, but it drop down to 6 k/s with the following IMQ rules.

iptables -t mangle -A FORWARD -i lan1 -j IMQ --todev 0   
iptables -t mangle -A FORWARD -i wan1 -j IMQ --todev 1

**Comment by gfreewind** [comment]
BTW, there is only two rules above working. The performance dives dramatically

**Comment by gfreewind** [comment]
Actually I did some changes for IMQ, it could enhance 25%. I don't know if you will accept the pull request. If so, I will send the pull request

**Comment by AdrianBan** [comment]
Hi,

You can send it and we can add it in the sources.

Regards,
--
Adrian Ban
IP/MPLS Engineer
-----------------------
mobil: +40788388190 / +32493524091
web: WWW.abtelecom.ro

**Comment by gfreewind** [comment]
Based on which kernel version?

**Comment by gfreewind** [comment]
Hi i have send the pull request based one 3.14.
