### ISSUE TITLE
kernel 4.14

### ISSUE THREAD

**Issue by PLumowina** [imq/linuximq#66]
Is someone working on patch that will work for new LTS kernel ?

**Comment by Roland-F** [comment]
With that patch i get during the startup an kernel-panic.
All settings for imq be identical to kernel 4.13.
I will get here:
Nov 23 21:33:37 fli4l kern.warn kKernel panic - not syncing: Aiee, killing interrupt handler!
CPU: 0 PID: 17004 Comm: tc Tainted: G        W       4.14.1-virt-nonfree #1
ernel: HTB: quanHardware name: FUJITSU                          D2963-S2                      /D2963-S2, BIOS 6.00 R1.22.2963.S2               12/01/2010
Call Trace:
 dump_stack+0x61/0x7d
tum of class 100 panic+0xe2/0x20f
 ? __mod_timer+0x1af/0x1d5
 do_exit+0x89/0x88a
007 is big. Cons ? add_timer+0x16/0x18
 ? queue_delayed_work_on+0x2c/0x31
 do_group_exit+0x3c/0x9d
 SyS_exit_group+0xf/0xf
 entry_SYSCALL_64_fastpath+0x1a/0xa5
RIP: 0033:0x7f02f27dede0
RSP: 002b:00007ffc118a66b8 EFLAGS: 00000246 ORIG_RAX: 00000000000000e7
RAX: ffffffffffffffda RBX: 00007ffc118a5670 RCX: 00007f02f27dede0
RDX: 0000000000000000 RSI: 00000000000000e7 RDI: 0000000000000000
RBP: 000000005a1730a3 R08: 0000000000000000 R09: 000000000000426c
R10: 00007f02f2a6a4c4 R11: 0000000000000246 R12: 00007ffc1189d5a0
R13: 00007ffc1189d5e0 R14: 0000000000652a40 R15: 0000000000000000
ider r2q change.Kernel Offset: disabled
---[ end Kernel panic - not syncing: Aiee, killing interrupt handler!

**Comment by imq** [comment]
Thanks, k0ste
