### ISSUE TITLE
New patch for kernel 5.0 not work

### ISSUE THREAD

**Issue by davidkek** [imq/linuximq#78]
Hi
i try to build with new kernel and imq but have problem:

CALL scripts/checksyscalls.sh
CC [M] drivers/net/imq.o
CC [M] drivers/net/tun.o
CC [M] drivers/net/nlmon.o
CC [M] drivers/net/sungem_phy.o
drivers/net/imq.c: In function 'nf_bridge_adjust_skb_data':
drivers/net/imq.c:409:11: error: 'struct sk_buff' has no member named 'nf_bridge'; did you mean 'nf_trace'?
if (skb->nf_bridge)
^~~~~~~~~
nf_trace
drivers/net/imq.c: In function 'nf_bridge_adjust_segmented_data':
drivers/net/imq.c:415:11: error: 'struct sk_buff' has no member named 'nf_bridge'; did you mean 'nf_trace'?
if (skb->nf_bridge)
^~~~~~~~~
nf_trace

**Comment by Roland-F** [comment]
Hello,
line "if (skb->nf_bridge)" must be exchanged with "if (nf_bridge_info_get(skb))"
Then it should work.
