### ISSUE TITLE
New patch for Kernel 5.3 need

### ISSUE THREAD

**Issue by Roland-F** [imq/linuximq#83]
Hello,
the actually patch for the kernel 5.2 will not fit to kernel 5.3 series.
New Version need.
Problem is by patching net/netfilter/nf_queue.c
point 2; 3 and 4.

**Comment by phl0** [comment]
Working on porting the patch to Linux 5.3 :-)

**Comment by phl0** [comment]
See: https://github.com/imq/linuximq/pull/84
