### ISSUE TITLE
imq patch 3.10 error during kernel compilation

### ISSUE THREAD

**Issue by zadziorrr** [imq/linuximq#87]
I need to use older kernel as newer not properly limiting bandwidth but kernel is getting error during compilation
linux-3.10.10 with linux-3.10-imq.diff, patch apply ok but compilation with error

In file included from include/linux/kernel.h:13:0,
                 from include/linux/cache.h:4,
                 from include/linux/time.h:4,
                 from include/linux/stat.h:18,
                 from include/linux/module.h:10,
                 from net/core/skbuff.c:41:
net/core/skbuff.c: In function ‘skb_release_head_state’:
net/core/skbuff.c:596:5: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     (unsigned int)skb->cb_next);
     ^
include/linux/printk.h:218:37: note: in definition of macro ‘pr_warning’
  printk(KERN_WARNING pr_fmt(fmt), ##__VA_ARGS__)
                                     ^
net/core/skbuff.c:595:4: note: in expansion of macro ‘pr_warn’
    pr_warn("IMQ: kfree_skb: skb->cb_next: %08x\n",
    ^
net/core/skbuff.c: In function ‘skb_init’:
net/core/skbuff.c:3129:14: error: invalid application of ‘sizeof’ to incomplete type ‘struct skb_cb_table’
       sizeof(struct skb_cb_table),
              ^
net/core/skbuff.c: At top level:
net/core/skbuff.c:3473:13: warning: ‘skb_copy_stored_cb’ defined but not used [-Wunused-function]
 static void skb_copy_stored_cb(struct sk_buff *new, const struct sk_buff *__old)
             ^
make[2]: *** [net/core/skbuff.o] Error 1
make[1]: *** [net/core] Error 2

the same with
linux-3.10.99 with linux-3.10-imq.diff
Please note also patch linux-3.10.27-imq.diff is malformed (look on patch size 4x bigger than others)
can anyone help ?

**Comment by imq** [comment]
what distro you have, and the kernel is downloaded from kernel.org or is from your distro ?

**Comment by zadziorrr** [comment]
Vanilla kernel from kernel.org
