### ISSUE TITLE
imq doesn't work on linux-3.14.77

### ISSUE THREAD

**Issue by leidemon** [imq/linuximq#90]
hi,imq team:
    I use imq to test QOS,and I was stacked with the issue:
I use the iptable-1.4.10 with imq patch, and kernel-3.14.77 with imq patch;
 and set the rule to test QOS, but it doesn't work. it is strange.
it seems the data is goto the imq0 a little, and most data goto the lan directly.
maybe it is releated to netfilter(kernel) or some buffer code?
Any advices?

**Comment by imq** [comment]
Hi, can you paste the rules and if you use NAT or no?

**Comment by leidemon** [comment]
hi,
Sorry for not replying for a long time；
iptables:
admin@Four-Faith:~# iptables -t mangle -nvL --line
Chain PREROUTING (policy ACCEPT 5265 packets, 1399K bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 1112 packets, 118K bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 748 packets, 331K bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1      363  310K IMQ        all  --  eth0   *       0.0.0.0/0            0.0.0.0/0           IMQ: todev 0 
2      748  331K SVQOS_htb  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
3      160  8192 TCPMSS     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           tcp flags:0x06/0x02 TCPMSS clamp to PMTU 

Chain OUTPUT (policy ACCEPT 83 packets, 7853 bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 828 packets, 339K bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain SVQOS_htb (1 references)
num   pkts bytes target     prot opt in     out     source               destination         
1      748  331K CONNMARK   all  --  *      *       0.0.0.0/0            0.0.0.0/0           CONNMARK restore 
2        0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           mark match !0x0/0xff 
3      748  331K CONNMARK   all  --  *      *       0.0.0.0/0            0.0.0.0/0           CONNMARK save 
4      748  331K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0   
tc qdisc 
qdisc htb 1: dev imq0 root refcnt 2 r2q 10 default 30 direct_packets_stat 0
qdisc sfq 100: dev imq0 parent 1:100 limit 127p quantum 16000b perturb 10sec 
qdisc sfq 10: dev imq0 parent 1:10 limit 127p quantum 16000b perturb 10sec 
qdisc red 20: dev imq0 parent 1:20 limit 1000000b min 5000b max 100000b ecn 
qdisc red 30: dev imq0 parent 1:30 limit 500000b min 2500b max 50000b ecn 
qdisc red 40: dev imq0 parent 1:40 limit 250000b min 1250b max 25000b ecn 
qdisc htb 1: dev eth0 root refcnt 5 r2q 10 default 30 direct_packets_stat 0
qdisc sfq 100: dev eth0 parent 1:100 limit 127p quantum 1514b perturb 10sec 
qdisc sfq 10: dev eth0 parent 1:10 limit 127p quantum 1514b perturb 10sec 
qdisc sfq 20: dev eth0 parent 1:20 limit 127p quantum 1514b perturb 10sec 
qdisc sfq 30: dev eth0 parent 1:30 limit 127p quantum 1514b perturb 10sec 
qdisc sfq 40: dev eth0 parent 1:40 limit 127p quantum 1514b perturb 10sec 
@imq ,waiting for your reply,thank you

**Comment by leidemon** [comment]
it is caused by shortcut_fe driver
