### ISSUE TITLE
No working IMQ-patch for kernel-line 5.9

### ISSUE THREAD

**Issue by Roland-F** [imq/linuximq#92]
The IMQ-patch from kernel 5.4 will not work with Kernel-line 5.9
So it is need to rework/modify the patch.
This is an new issue identical as #89 for Kernel-line 5.7 and 5.8

**Comment by Roland-F** [comment]
Hello,
with the attached patch i was be able to have linux-imq running.
This patch will work with kernel-line 5.8 and 5.9
Today i made a test and see that it will work complete.

[10-imq.patch.txt](https://github.com/imq/linuximq/files/5647238/10-imq.patch.txt)

**Comment by imq** [comment]
Thanks @Roland-F for the patch, can i ask you to do PR.

**Comment by Roland-F** [comment]
Hello,

sorry i am not firm in that thinks.

So I cannot do this.

 

BR, Roland

 

Von: MihaiC <notifications@github.com> 
Gesendet: Samstag, 5. Dezember 2020 19:45
An: imq/linuximq <linuximq@noreply.github.com>
Cc: Roland-F <fli4l@franke-prem.de>; Mention <mention@noreply.github.com>
Betreff: Re: [imq/linuximq] No working IMQ-patch for kernel-line 5.9 (#92)

 

Thanks @Roland-F <https://github.com/Roland-F>  for the patch, can i ask you to do PR.

**Comment by imq** [comment]
@Roland-F I don't understand what you mean

**Comment by Roland-F** [comment]
Hello,

and i will not understand what you mean with the “PR”.

 

I am not firm with git and what must be done to give you an patch in git.



 

Von: MihaiC <notifications@github.com> 
Gesendet: Samstag, 5. Dezember 2020 20:04
An: imq/linuximq <linuximq@noreply.github.com>
Cc: Roland-F <fli4l@franke-prem.de>; Mention <mention@noreply.github.com>
Betreff: Re: [imq/linuximq] No working IMQ-patch for kernel-line 5.9 (#92)

 

@Roland-F <https://github.com/Roland-F>  I don't understand what you mean

**Comment by imq** [comment]
PR mean Pull Request.

It's ok I will add the patch manually. Thanks for the patch and testing!
