### ISSUE TITLE
new patch for kernel 6.9.x line is need

### ISSUE THREAD

**Issue by Roland-F** [imq/linuximq#97]
With the kernel-change "netfilter: move nf_reinject into nfnetlink_queue modules"
(See https://github.com/torvalds/linux/commit/3f801968889459ecae1eab524b039676e6eaa319)
the actual linux-imq patch will not longer fit.
Is here anyone who can solve the problem?

**Comment by Roland-F** [comment]
Can it be that there is the file net/netfilter/nfnetlink_queue.h in your patch is missing?
I will not see that it is inside your patch and also not include at the kernel-src.

**Comment by imq** [comment]
i will re-upload to correct one, thx for the feedbak

**Comment by Roland-F** [comment]
The new patch will build also with Kernel 6.10.9
